version: 2

models:

  - name: stg_btc
    columns:
      - name: HASH_KEY
        tests:
          - unique
          - not_null

  - name: stg_btc_outputs
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('stg_btc_outputs_py')

  - name: whale_alert
    columns:
    - name: output_address
      data_tests:
        - assert_valid_btc_address
